[package]
name = "blacktorrent"
version = "0.1.0"
edition = "2024"

[dependencies]
tracker = "0.2.2"
thiserror = "2.0.12"
lazy_static = "1.5.0"
rand = "0.9.1"
tokio = { version = "1.45.0", features = ["full"] }
